### ISSUE TITLE
ifc.client.verifyPayment always return false

### ISSUE THREAD

**Issue by white87332** [TideiSunTaipei/infinitechain_browser#1]
Because check value of ifc.client.getRawPayment is null, so ifc.client.verifyPayment function  returns false.

1.I think that is a bug
2.expected verifyPayment function return true
3.infinitechain version 0.0.7
4.macos, node version 9.5.0
5.broswer is chrome v64.0.3282.186

**Comment by BenjaminLu** [comment]
It seems to me that there may not exist the target paymentHash in your local storage. You probably forgot to execute the `ifc.client.saveRawPayment(rawPayment)` function before sending the raw payment to server.

**Comment by white87332** [comment]
Hi, I had executed `ifc.client.saveRawPayment(rawPayment)`.
![2018-03-02 10 56 23](https://user-images.githubusercontent.com/2655810/36881401-e08aaf5c-1e08-11e8-8ccb-73ecff9011f6.png)

**Comment by RaymondHong** [comment]
Currently I executed ifc.client. makeRawPayment(rawPayment) and the result with no key "form" and "to" in this result (because the scenario doesn't set form and to eth address)

**Comment by white87332** [comment]
I got a correct response, thank you!
